// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title FrensPlan - who the frens' contracts are made for, and where they land
/// @notice GENERATED by script/placement/gen.py: never edit by hand. The salts are mined so the frens and the swapper
///         start 0x6900…; the addresses follow from them, the standard CREATE2 deployer and FrensCode.
library FrensPlan {
    /// @notice The standard CREATE2 deployer (Arachnid's, the same address on every chain)
    address internal constant CREATE2_DEPLOYER = 0x4e59b44847b379578588920cA78FbF26c0B4956C;
    address internal constant OWNER = 0x35dA9C0303507ddf708E87F2568EdDf12c47a059;
    address internal constant IMD = 0xD34a99Bc0f67aE1bbd63C660e6d0b0dd03E263B7;
    address internal constant IMD6900 = 0x0000198C940D8cD70Cb9ACeC5E3af8216ac57d2F;
    address internal constant IDENTITY = 0x0000eC93127BAA929E58E97dd0095A2BFb38ec1D;
    address internal constant PERMIT2 = 0x000000000022D473030F116dDEE9F6B43aC78BA3;
    address internal constant X402_PROXY = 0x402085c248EeA27D92E8b30b2C58ed07f9E20001;
    address internal constant IMD_PAY_TO = 0xC94400e90bB652AFA02740bFf50824E14069c133;
    address internal constant KEEPER = 0x75521bC4b21CAFD5bbc008A76D0988f777BD5888;
    address internal constant RELAYER = 0x3c038c9D0ab5532b5cae78dABeda916e34af3D5E;
    address internal constant POOL_MANAGER = 0x000000000004444c5dc75cB358380D2e3dE08A90;
    address internal constant PAIR_HOOK = 0x667f4621030aCfAfb1bD0B64d33610A8567f2A44;
    address internal constant POOL4_HOOK = 0xc6C965Bd164c483e87d0B550671798e9A3602840;
    bytes32 internal constant PRICES_SALT = 0x0000000000000000000000000000000000000000000000000000000000000001;
    bytes32 internal constant FRENS_SALT = 0x4f900cd477e15b6a5c2e9edf0a3895d76748f008e47cd76826508e63a3489a05;
    bytes32 internal constant SWAPPER_SALT = 0x290c57874c15123599b99c6137a098446d68170e903a27ac1676d8a76eaf8233;
    bytes32 internal constant MINTER_SALT = 0x0000000000000000000000000000000000000000000000000000000000000002;
    bytes32 internal constant GATE_SALT = 0x0000000000000000000000000000000000000000000000000000000000000003;
    /// @notice where it lands on Ethereum (any chain with the CREATE2 deployer)
    address internal constant PRICES_AT = 0x8f135B75Df156e6346c8525E138bC2BD652146ff;
    /// @notice where it lands on Ethereum (any chain with the CREATE2 deployer)
    address internal constant FRENS_AT = 0x6900d042460d6bdbe68CE994F4dE36706797CCd4;
    /// @notice where it lands on Ethereum (any chain with the CREATE2 deployer)
    address internal constant SWAPPER_AT = 0x69002297DD7980af0d24249f6a44E7046B1Cb1fb;
    /// @notice where it lands on Ethereum (any chain with the CREATE2 deployer)
    address internal constant MINTER_AT = 0x46B50a3061Ea692e075231c13bc653FdD1Bedd29;
    /// @notice where it lands on Ethereum (any chain with the CREATE2 deployer)
    address internal constant GATE_AT = 0xF83807Ec2E27e1771Fb2594139c1F6925Cfd9B8E;
}
